/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as ContributeIndexRouteImport } from './routes/contribute.index'
import { Route as ContributeFacilityIdRouteImport } from './routes/contribute.$facilityId'
import { Route as FacilityIdRouteImport } from './routes/facility.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeIndexRoute = ContributeIndexRouteImport.update({
  id: '/contribute/',
  path: '/contribute/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeFacilityIdRoute = ContributeFacilityIdRouteImport.update({
  id: '/contribute/$facilityId',
  path: '/contribute/$facilityId',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityIdRoute = FacilityIdRouteImport.update({
  id: '/facility/$id',
  path: '/facility/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/discover': typeof DiscoverRoute
  '/ecosystem': typeof EcosystemRoute
  '/insights': typeof InsightsRoute
  '/ops': typeof OpsRoute
  '/preferences': typeof PreferencesRoute
  '/review': typeof ReviewRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/contribute/$facilityId': typeof ContributeFacilityIdRoute
  '/facility/$id': typeof FacilityIdRoute
  '/contribute/': typeof ContributeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/discover': typeof DiscoverRoute
  '/ecosystem': typeof EcosystemRoute
  '/insights': typeof InsightsRoute
  '/ops': typeof OpsRoute
  '/preferences': typeof PreferencesRoute
  '/review': typeof ReviewRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/contribute/$facilityId': typeof ContributeFacilityIdRoute
  '/facility/$id': typeof FacilityIdRoute
  '/contribute': typeof ContributeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/discover': typeof DiscoverRoute
  '/ecosystem': typeof EcosystemRoute
  '/insights': typeof InsightsRoute
  '/ops': typeof OpsRoute
  '/preferences': typeof PreferencesRoute
  '/review': typeof ReviewRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/contribute/$facilityId': typeof ContributeFacilityIdRoute
  '/facility/$id': typeof FacilityIdRoute
  '/contribute/': typeof ContributeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/discover'
    | '/ecosystem'
    | '/insights'
    | '/ops'
    | '/preferences'
    | '/review'
    | '/auth/confirm'
    | '/contribute/$facilityId'
    | '/facility/$id'
    | '/contribute/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/discover'
    | '/ecosystem'
    | '/insights'
    | '/ops'
    | '/preferences'
    | '/review'
    | '/auth/confirm'
    | '/contribute/$facilityId'
    | '/facility/$id'
    | '/contribute'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/discover'
    | '/ecosystem'
    | '/insights'
    | '/ops'
    | '/preferences'
    | '/review'
    | '/auth/confirm'
    | '/contribute/$facilityId'
    | '/facility/$id'
    | '/contribute/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  DiscoverRoute: typeof DiscoverRoute
  EcosystemRoute: typeof EcosystemRoute
  InsightsRoute: typeof InsightsRoute
  OpsRoute: typeof OpsRoute
  PreferencesRoute: typeof PreferencesRoute
  ReviewRoute: typeof ReviewRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  ContributeFacilityIdRoute: typeof ContributeFacilityIdRoute
  FacilityIdRoute: typeof FacilityIdRoute
  ContributeIndexRoute: typeof ContributeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute/': {
      id: '/contribute/'
      path: '/contribute'
      fullPath: '/contribute/'
      preLoaderRoute: typeof ContributeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute/$facilityId': {
      id: '/contribute/$facilityId'
      path: '/contribute/$facilityId'
      fullPath: '/contribute/$facilityId'
      preLoaderRoute: typeof ContributeFacilityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility/$id': {
      id: '/facility/$id'
      path: '/facility/$id'
      fullPath: '/facility/$id'
      preLoaderRoute: typeof FacilityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  DiscoverRoute: DiscoverRoute,
  EcosystemRoute: EcosystemRoute,
  InsightsRoute: InsightsRoute,
  OpsRoute: OpsRoute,
  PreferencesRoute: PreferencesRoute,
  ReviewRoute: ReviewRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  ContributeFacilityIdRoute: ContributeFacilityIdRoute,
  FacilityIdRoute: FacilityIdRoute,
  ContributeIndexRoute: ContributeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
